### ISSUE TITLE
Different Flow Import Issue

### ISSUE THREAD

**Issue by ballbrianm** [ben-howard/Planner-PowerBI-with-PowerAutomate#11]
Hi @ben-howard, came across the attached error when trying to import the flow. Watched both videos and tried using both flow templates, but neither is importing. Any idea what is causing this error? Also, with the original flow, I am getting the other 'GetTable' error but without the option to save as a new flow, so I can't bypass the error.

![Screenshot 2022-12-01 121029](https://user-images.githubusercontent.com/107218410/205116306-ff9ff868-6090-491b-9bd2-0aae9846be50.png)

**Comment by ben-howard** [comment]
Hi, I have never been able to consistently import flows; I am left thinking that where the exported flow uses something specific tables or scripts etc then it does not always work.  The only thing I can recommend at this stage is to create the flow from scratch using the PDFs
