### ISSUE TITLE
Remove_existing_x_rows actions fail with conflict errors 

### ISSUE THREAD

**Issue by Julianne-Johnson** [ben-howard/Planner-PowerBI-with-PowerAutomate#12]
Hi Ben,

In the Office Scripts version of the "Add Planner tasks to an Excel Online Business spreadsheet" flow I'm getting conflict errors on almost every run.  They always happen on the first steps that delete existing rows out of the Excel workbook.  Here's an example:

![image](https://user-images.githubusercontent.com/26280309/206227182-6ac28215-a7f9-4abd-acef-1985f898ca74.png)

The steps are automatically retrying, and sometimes the second try works, but most times it doesn't.  There shouldn't be anything using the target workbook except for this flow at the time.  Can you suggest an adjustment to the flow so I can keep the different branches bumping into each other?

**Comment by ben-howard** [comment]
Merging is because the online version and the desktop version need to be merged together.  Probably worth closing the desktop version, making sure everything is updated and synch'd in OneDrive, and then running the flow again.
