### ISSUE TITLE
Have a excel one excel script

### ISSUE THREAD

**Issue by Jaz939** [ben-howard/Planner-PowerBI-with-PowerAutomate#14]
Hi Ben,
If you are still following this tutorial and comment, then this is great.

I would like to contribute to this tutorial and share with you excel script that will delete all content in table at once. With this you can in Power automate after the trigger delete the table contents and then branch the task of the automatization.
script:
 function main(workbook: ExcelScript.Workbook) {
    //Get tables
    let tables = workbook.getTables();

    //Delete all rows in all tables
    tables.forEach(table => {
        let numberOfRows = table.getRowCount();
        if (numberOfRows > 0) table.getRangeBetweenHeaderAndTotal().delete(0);
    })

}

Thanks of the tutorial.
BR
Roman

**Comment by ben-howard** [comment]
Hi Roman, thank you so much for this, I will include it in my next iteration of this flow.

From: Jaz939 ***@***.***>
Sent: 08 April 2023 14:58
To: ben-howard/Planner-PowerBI-with-PowerAutomate ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ben-howard/Planner-PowerBI-with-PowerAutomate] Have a excel one excel script (Issue #14)


Hi Ben,
If you are still following this tutorial and comment, then this is great.

I would like to contribute to this tutorial and share with you excel script that will delete all content in table at once. With this you can in Power automate after the trigger delete the table contents and then branch the task of the automatization.
script:
function main(workbook: ExcelScript.Workbook) {
//Get tables
let tables = workbook.getTables();

//Delete all rows in all tables

tables.forEach(table => {

    let numberOfRows = table.getRowCount();

    if (numberOfRows > 0) table.getRangeBetweenHeaderAndTotal().delete(0);

})

}

Thanks of the tutorial.
BR
Roman
