### ISSUE TITLE
Duplicate Tasks Populating with Flow

### ISSUE THREAD

**Issue by Harker12** [ben-howard/Planner-PowerBI-with-PowerAutomate#15]
I have been able to get the flow to work and now my tasks are duplicating for some reason.  Attached are photos of my excel and the error notification PBI is giving me when importing the excel.

![Duplicating Tasks](https://user-images.githubusercontent.com/130391065/230951158-94faa14b-f84f-4108-a4b8-cf9c96262908.png)

![Error Notification](https://user-images.githubusercontent.com/130391065/230952125-6f81c7fe-847c-4df4-9e79-4b8e03ceb223.png)

**Comment by ben-howard** [comment]
So either multiple flows are running at once, or the rows in the table are not being deleted.  It's worth opening the excel file in a browser in the tasks worksheet, and then running the flow.  The table should empty, if not, check that you've set up the flow correctly for this particular table - from memory, you should be calling the script called "Remove_tasks"

**Comment by Harker12** [comment]
It is deleting the table.   I watched it earlier today.

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ben-howard** [comment]
Interesting.  The screen shots so at least 7 repetitions of each line.  So the flow is writing at least 7 times into the same table. It would suggest to me that the flow isn’t set up correctly, that’s where I’d start my investigation
