### ISSUE TITLE
Sequential folder contains Single Team parallel flow

### ISSUE THREAD

**Issue by JayDeeJaye** [ben-howard/Planner-PowerBI-with-PowerAutomate#16]
Planner-PowerBI-with-PowerAutomate-main > Sequential sub-directory contains the SingleTeam-AddPlannertaskstoanExcelOnlineBusinessspreadsheet.zip package archive.  The resulting import is a parallel flow, not the sequential flow documented in the PlannerFlow - Sequential map.pdf

**Comment by ben-howard** [comment]
Thanks for bringing this to my attention.  I've resolved the issue.
