### ISSUE TITLE
Tasks importing

### ISSUE THREAD

**Issue by Girakun74** [ben-howard/Planner-PowerBI-with-PowerAutomate#19]
Hello Ben, 
first of all it's a great template.
Please help me with an issue. In our planner we have set recurring tasks. 
When importing takes to long time to get every future tasks. 
Is there a possibility to limit the imported tasks for the next few months only.
Thanks in advance.

**Comment by ben-howard** [comment]
Hi, you could probably add a condition once you have retrieved the task, to check if the date, and if it fell into a range then write the task into the Excel, if not, ignore it.  However, I am not sure how much this would speed up the flow, as the only piece you would save is the writing of the task into Excel.

**Comment by Girakun74** [comment]
I wonder if I can add a condition in the flow that limits the imported data,
