### ISSUE TITLE
Power BI - Null

### ISSUE THREAD

**Issue by ManUSoccerFan** [ben-howard/Planner-PowerBI-with-PowerAutomate#5]
When I put this in Power BI I get a string of errors. One is the OLE DB or ODBC error and I am asked to refresh for the new query connections and once I do that it I get this 

column 'plan id' in table 'plan_tbl' contains a duplicate value 'ar48a8o3c0gmexkav1e7t5yagqcd' and this is not allowed for columns on the one side of a many-to-one relationship or for columns that are used as the primary key of a table.

then it says it call read a null. Help would be appreciated.

**Comment by ben-howard** [comment]
This is becuase for sometimes, for some reason, the plan_tbl does not have all rows removed.  Please run the flow again, ensuring that only a single flow runs at once, and that all rows are removed from the table (you can watch them empty from the table whilst the flow is running).  If the flow does not fully emply the table, yo ucan manually remove all the rows from the rable (but do not delete the table itself).  There are more comments @ https://www.youtube.com/watch?v=-U1Nnj95VMo
