### ISSUE TITLE
Can´t find the scripts in the excel table

### ISSUE THREAD

**Issue by juanbe65** [ben-howard/Planner-PowerBI-with-PowerAutomate#6]
I Can´t find the script in the excel table

Can you help me?

**Comment by ben-howard** [comment]
Have you saved the Excel file in SharePoint?

**Comment by juanbe65** [comment]
I saved it in one-drive.  
Another way, in the excel file there aren´t any macro or VB code. It´s correct?

**Comment by ben-howard** [comment]
Okay, it needs to be saved in a sharepoint document library.  And it is not VBA or a Macro, it is Office Scripts.  Please read this URL to understand more.  https://support.microsoft.com/en-us/office/introduction-to-office-scripts-in-excel-9fbe283d-adb8-4f13-a75b-a81c6baf163a
